#!/bin/sh

die () {
    echo >&2 "$@"
    exit 1
}

dir="$1"

[ "$#" -eq 1 ] || echo "No arguments passed, using current working directory ($PWD)" ; dir="$PWD"
[ -d "$dir" ] || die "Directory $dir does not exist"

mkdir -p $CONDA_PREFIX/etc/conda/activate.d
mkdir -p $CONDA_PREFIX/etc/conda/deactivate.d

touch $CONDA_PREFIX/etc/conda/activate.d/set_wd.sh ; echo "cd $dir" > $CONDA_PREFIX/etc/conda/activate.d/set_wd.sh
touch $CONDA_PREFIX/etc/conda/deactivate.d/unset_wd.sh ; echo "cd" > $CONDA_PREFIX/etc/conda/deactivate.d/unset_wd.sh
